# Sets user-defined palette
palette = "catppuccin_mocha"

# Setups

format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_status\
${custom.git_email}\
$java\
$kotlin\
$bun\
$nodejs\
$python\
$rust\
$golang\
$terraform\
$pulumi\
$fill"""

right_format  = """
$docker_context\
$kubernetes\
$aws\
$gcloud\
$cmd_duration"""

add_newline = false 

[character]
success_symbol = "[ó°˜§](green)"
error_symbol = "[î¯¦](pink)"
vicmd_symbol = "[ğŸš€](peach)"

[fill]
symbol = ' '
style = "bg:base fg:text"

[directory]
truncation_length = 3
truncation_symbol = 'â€¦/'
format = "[$path ](bg:base fg:lavender bold)"
style = "bg:none fg:base"

[directory.substitutions]
"~/projects/" = "ğŸ“š "

[cmd_duration]
format = " took [$duration]($style)"
style = "bg:base fg:text"

[bun]
format = "[ ó°‡ ](bg:base fg:text bold)[ğŸ$version](bg:base fg:peach)"
version_format = " v${raw}"

[nodejs]
format = "[ó°‡ ](bg:base fg:text bold)[$symbol($version)](bg:base fg:green)"
version_format = " v${major}"
symbol = "îœ˜"
style = "bg:base fg:text"
detect_files = [
    ".node-version",
    ".nvmrc",
    "!bunfig.toml",
    "!bun.lockb"
]
detect_folders = [""]

[terraform]
format = "[ ó°º ](bg:base fg:text bold)[îšš $workspace](bg:base fg:sapphire)"

[pulumi]
format = "[ ó°º ](bg:base fg:text bold)[$symbol$stack]($style)"
style = "bg:base fg:red"

[docker_context]
format = "via [ó°¡¨ $context]($style)"
style = "bg:none fg:mauve"

[kubernetes]
format = "[ó±ƒ¾  $namespace â‰· $context âˆ«]($style)"
disabled = false
style = "bg:none fg:mauve"

[[kubernetes.contexts]]
context_pattern  = "kind-.*"
context_alias = "ï’³"

[[kubernetes.contexts]]
context_pattern  = "project-(?P<cluster>[\\w-]+)"
context_alias = "$cluster"

[[kubernetes.contexts]]
context_pattern  = ".*/az/.*"
context_alias = "az"

[[kubernetes.contexts]]
context_pattern  = "arn:.*.:.*.:.*.:.*.:.*/(?P<cluster>[\\w-]+)"
context_alias = "AWS::${1}cluster"

[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<cluster>[\\w-]+)"
context_alias = "gke-$cluster"


[aws]
format = '[$symbol$profileâ($region)âŒ‹]($style)'
style = "bg:none fg:yellow"
symbol = 'ó°¸ âŒˆ'
[aws.region_aliases]
sa-east-1 = "sp1"
us-east-1 = "us1"
us-east-2 = "us2"
[aws.profile_aliases]
Zamp-PRD = 'zamp-prd'
default = 'zero'

[gcloud]
disabled = true
format = "[$symbol$active]($style) "
style = "bg:none fg:yellow"

[git_branch]
format = "[on $symbol$branch ]($style)"
symbol = "ï˜ "
style = "bg:base fg:teal bold"

[git_status]
# $all status$ahead_behind
format = "[ $all_status$ahead_behind](bg:base fg:yellow)"
style = "bg:none fg:base"
conflicted = "="
ahead =	"â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
up_to_date = "ï˜«"
untracked = "?${count}"
stashed = "ï£•"
modified = "!${count}"
staged = "+${count}"
renamed = "Â»${count}"
deleted = "ï™•${count}"
disabled = true

[custom.git_email]
disabled = true
command = "git config user.email | sed 's/.*@//'"
when = "git rev-parse --git-dir 2> /dev/null"
format = " [$output]($style) Â¦"
style = "bright-yellow italic"

[custom.giturl]
disabled = true
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL="ïˆ "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL="ïŠ– "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL="ï…± "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL="ï¡ "
else
    GIT_REMOTE_SYMBOL="ï‡’ "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = "git rev-parse --is-inside-work-tree 2> /dev/null"
format = "at $output  "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
